<?php

declare(strict_types=1);

/**
 * @file
 * Primary module hooks for moneylink_logout module.
 */

/**
 * Implements hook_theme().
 */
function moneylink_logout_theme(): array {
  return [
    'logouttemplate' => [
      'variables' => ['foo' => NULL],
    ],
  ];
}

/**
 * Prepares variables for logouttemplate.html.twig template.
 *
 * Default template: logouttemplate.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_logouttemplate(array &$variables): void {
  $variables['foo'] = 'bar';
}
