<?php

declare(strict_types=1);

/**
 * @file
 * Primary module hooks for hola_mundo module.
 */

/**
 * Implements hook_theme().
 */
function money_link_theme(): array
{
  return [
    'loginformtemplate' => [
      'template' => 'loginformtemplate',
      'variables' => ['loginform' => NULL],
    ],
    'userpaneltemplate' => [
      'variables' => [
        'user' => NULL,
        'token' => NULL,
      ]
    ],
    'adminpaneltemplate' => [
      'variables' => [
        'user' => NULL,
        'token' => NULL
      ],
    ],
    'logouttemplate2' => [
      'variables' => ['foo' => NULL],
    ],
    'hometemplate' => [
      'variables' => ['foo' => NULL],
    ],
  ];
}

/**
 * Prepares variables for holamundotemplate.html.twig template.
 *
 * Default template: holamundotemplate.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_holamundotemplate(array &$variables): void
{
  //
}


/**
 * Prepares variables for userpaneltemplate.html.twig template.
 *
 * Default template: userpaneltemplate.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_userpaneltemplate(array &$variables): void
{
  //
}

/**
 * Prepares variables for adminpaneltemplate.html.twig template.
 *
 * Default template: adminpaneltemplate.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_adminpaneltemplate(array &$variables): void
{
  //
}
/**
 * Prepares variables for logouttemplate.html.twig template.
 *
 * Default template: logouttemplate.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_logouttemplate(array &$variables): void
{
  //
}

/**
 * Prepares variables for hometemplate.html.twig template.
 *
 * Default template: hometemplate.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_hometemplate(array &$variables): void
{
  $variables['foo'] = 'bar';
}
